message=t123123123232
classpath_mapping=classpath:/META-INF/resources/
url_mapping=file:${user.home}/show-videos-dev-data/
logging.file=${user.home}/show-videos-dev-data/logs/application.log
logging.level.org.org.springframework.web=ERROR